apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
  namespace: aegisshield
data:
  neo4j.conf: |
    # Neo4j 5+ Configuration for AegisShield Graph Engine
    # Constitutional Principle: Data Integrity & Scalability
    
    # Network connector configuration
    server.default_listen_address=0.0.0.0
    server.bolt.listen_address=0.0.0.0:7687
    server.http.listen_address=0.0.0.0:7474
    server.https.listen_address=0.0.0.0:7473
    
    # Database configuration
    server.memory.heap.initial_size=1G
    server.memory.heap.max_size=2G
    server.memory.pagecache.size=1G
    
    # Security configuration
    dbms.security.auth_enabled=true
    dbms.ssl.policy.bolt.enabled=true
    dbms.ssl.policy.https.enabled=true
    
    # Logging for audit compliance
    server.logs.user.level=INFO
    server.logs.security.level=INFO
    dbms.logs.query.enabled=true
    dbms.logs.query.threshold=100ms
    
    # Performance tuning for graph queries
    dbms.query_cache_size=256M
    dbms.query.memory.max=2G
    cypher.runtime=pipelined
    
    # Clustering (for HA deployment)
    # causal_clustering.minimum_core_cluster_size_at_formation=3
    # causal_clustering.minimum_core_cluster_size_at_runtime=3
    # causal_clustering.initial_discovery_members=neo4j-0.neo4j.aegisshield.svc.cluster.local:5000,neo4j-1.neo4j.aegisshield.svc.cluster.local:5000,neo4j-2.neo4j.aegisshield.svc.cluster.local:5000
---
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-secret
  namespace: aegisshield
type: Opaque
stringData:
  NEO4J_AUTH: "neo4j/CHANGE_ME_IN_PRODUCTION"  # Use Vault in production
  NEO4J_DATABASE: "aegisshield"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: aegisshield
  labels:
    app: neo4j
    component: graph-database
spec:
  serviceName: neo4j
  replicas: 1  # Scale to 3 for HA clustering in production
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
        component: graph-database
    spec:
      serviceAccountName: aegisshield-admin
      containers:
      - name: neo4j
        image: neo4j:5.12-enterprise  # Use community edition if no enterprise license
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7473
          name: https
        - containerPort: 7687
          name: bolt
        - containerPort: 5000
          name: discovery
        - containerPort: 6000
          name: raft
        - containerPort: 7000
          name: tx
        env:
        - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
          value: "yes"
        - name: NEO4J_EDITION
          value: "enterprise"  # Change to "community" if needed
        envFrom:
        - secretRef:
            name: neo4j-secret
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: neo4j-logs
          mountPath: /logs
        - name: neo4j-config
          mountPath: /var/lib/neo4j/conf/neo4j.conf
          subPath: neo4j.conf
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /
            port: 7474
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 7474
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: neo4j-config
        configMap:
          name: neo4j-config
  volumeClaimTemplates:
  - metadata:
      name: neo4j-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Gi  # Graph data can grow significantly
  - metadata:
      name: neo4j-logs
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: aegisshield
  labels:
    app: neo4j
    component: graph-database
spec:
  ports:
  - port: 7474
    targetPort: 7474
    name: http
  - port: 7473
    targetPort: 7473
    name: https
  - port: 7687
    targetPort: 7687
    name: bolt
  selector:
    app: neo4j
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-cluster
  namespace: aegisshield
  labels:
    app: neo4j
    component: graph-database
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: discovery
  - port: 6000
    targetPort: 6000
    name: raft
  - port: 7000
    targetPort: 7000
    name: tx
  selector:
    app: neo4j
  clusterIP: None  # Headless service for clustering