apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "/etc/prometheus/rules/*.yml"
    
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093
    
    scrape_configs:
      # Prometheus self-monitoring
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      # Kubernetes API server
      - job_name: 'kubernetes-apiserver'
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https
      
      # Kubernetes nodes
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics
      
      # Kubernetes pods
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
      
      # AegisShield Services
      - job_name: 'aegisshield-api-gateway'
        static_configs:
          - targets: ['api-gateway:8080']
        metrics_path: /metrics
        scrape_interval: 10s
        
      - job_name: 'aegisshield-data-ingestion'
        static_configs:
          - targets: ['data-ingestion:8060']
        metrics_path: /metrics
        scrape_interval: 10s
        
      - job_name: 'aegisshield-graph-engine'
        static_configs:
          - targets: ['graph-engine:8065']
        metrics_path: /metrics
        scrape_interval: 10s
        
      - job_name: 'aegisshield-entity-resolution'
        static_configs:
          - targets: ['entity-resolution:8061']
        metrics_path: /metrics
        scrape_interval: 10s
        
      - job_name: 'aegisshield-alerting-engine'
        static_configs:
          - targets: ['alerting-engine:8062']
        metrics_path: /metrics
        scrape_interval: 10s
        
      - job_name: 'aegisshield-user-management'
        static_configs:
          - targets: ['user-management:8063']
        metrics_path: /metrics
        scrape_interval: 10s
        
      - job_name: 'aegisshield-analytics-dashboard'
        static_configs:
          - targets: ['analytics-dashboard:8066']
        metrics_path: /metrics
        scrape_interval: 10s
        
      - job_name: 'aegisshield-reporting'
        static_configs:
          - targets: ['reporting:8067']
        metrics_path: /metrics
        scrape_interval: 10s
      
      # Database monitoring
      - job_name: 'postgresql'
        static_configs:
          - targets: ['postgres-exporter:9187']
        scrape_interval: 15s
        
      - job_name: 'neo4j'
        static_configs:
          - targets: ['neo4j:2004']
        metrics_path: /metrics
        scrape_interval: 15s
        
      - job_name: 'kafka'
        static_configs:
          - targets: ['kafka-exporter:9308']
        scrape_interval: 15s
        
      # Infrastructure monitoring
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_endpoints_name]
            regex: 'node-exporter'
            action: keep