apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: aegisshield
type: Opaque
data:
  # Base64 encoded values (these should be replaced with actual encoded secrets)
  postgresql-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWw6NTQzMi9hZWdpc3NoaWVsZA==
  neo4j-url: Ym9sdDovL25lbzRqOjc2ODc=
  neo4j-user: bmVvNGo=
  neo4j-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: aegisshield
type: Opaque
data:
  # Base64 encoded JWT secret (replace with actual secret)
  jwt-secret: YWVnaXNzaGllbGQtand0LXNlY3JldC1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
  namespace: aegisshield
type: Opaque
data:
  # Base64 encoded Kafka credentials
  kafka-user: a2Fma2E=
  kafka-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aegisshield-config
  namespace: aegisshield
data:
  # Application configuration
  log-level: "info"
  max-connections: "1000"
  timeout-seconds: "30"
  
  # Service URLs (internal cluster communication)
  data-ingestion-url: "data-ingestion-service:8060"
  entity-resolution-url: "entity-resolution-service:8061"
  alerting-engine-url: "alerting-engine-service:8062"
  graph-engine-url: "graph-engine-service:8063"
  api-gateway-url: "api-gateway-service:8080"
  
  # External service URLs
  kafka-brokers: "kafka:9092"
  postgresql-host: "postgresql"
  postgresql-port: "5432"
  neo4j-host: "neo4j"
  neo4j-port: "7687"
  
  # Feature flags
  enable-ml-features: "true"
  enable-graph-analytics: "true"
  enable-real-time-alerts: "true"
  
  # Performance tuning
  worker-pool-size: "10"
  batch-size: "1000"
  cache-ttl: "3600"
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: aegisshield
type: kubernetes.io/dockerconfigjson
data:
  # Base64 encoded Docker registry credentials
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJhZWdpc3NoaWVsZCIsInBhc3N3b3JkIjoicmVnaXN0cnktcGFzc3dvcmQiLCJhdXRoIjoiWVdWbmFYTnphR2xsYkdRNmNtVm5hWE4wY25rdGNHRnpjM2R2Y21RPSJ9fX0=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegisshield-sa
  namespace: aegisshield
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: aegisshield
  name: aegisshield-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aegisshield-rolebinding
  namespace: aegisshield
subjects:
- kind: ServiceAccount
  name: aegisshield-sa
  namespace: aegisshield
roleRef:
  kind: Role
  name: aegisshield-role
  apiGroup: rbac.authorization.k8s.io